name: "{{name.snakeCase()}}"
description: "{{description}}"
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal Packages

  # External Packages

dev_dependencies:
  flutter_test:
    sdk: flutter

  # External dev dependencies
  auto_route_generator: 10.2.3
  build_runner: 2.5.4
  injectable_generator: 2.7.0
  mocktail: 1.0.2

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
